name: delve-into-job
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    name: First Job
    steps:
      - name: Run First
        run: echo "Running first"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Test
        run: npm run test
    
  second-job:
    runs-on: ubuntu-latest
    name: Second Job
    needs: first-job
    steps:
      - name: Run Second
        run: echo "Running second"
